import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by pxng.online",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Link href="/"><button className="px-4 bg-blue-500 hover:bg-blue-400 ">home</button></Link>
      <Link href="/api"><button className="px-4 bg-blue-500 hover:bg-blue-400 ">api</button></Link>
      <Link href="/users/9"><button className="px-4 bg-blue-500 hover:bg-blue-400 ">users</button></Link>
      <Link href="/test/id/name"><button className="px-4 bg-blue-500 hover:bg-blue-400">test</button></Link>
      <Link href="/todo-list"><button className="px-4 bg-blue-500 hover:bg-blue-400">todo</button></Link>
      <Link href="/todo-list/client"><button className="px-4 bg-blue-500 hover:bg-blue-400">todo-client</button></Link>
      <Link href="/login"><button className="px-4 bg-blue-500 hover:bg-blue-400">login</button></Link>
        {children}
      </body>
    </html>
  );
}
